version: '3.8'

services:
  crm-web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - my_network

  db:
    container_name: db
    platform: linux/amd64
    image: postgres:15.0
    restart: always
    environment:
      POSTGRES_DB: "crm"
      POSTGRES_USER: "crm"
      POSTGRES_PASSWORD: "crm"
    ports:
      - 5432:5432
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
