# Generated by Django 4.1.1 on 2023-09-12 06:59

import wagtail.fields
from django.db import migrations

import cms.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0003_remove_blogdetailpage_show_legend_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogdetailpage",
            name="content",
            field=wagtail.fields.StreamField(
                [
                    ("content_title", cms.blocks.BlogContentTitleBlock()),
                    ("code", cms.blocks.BlogCodeBlock()),
                    ("rich_text", cms.blocks.BlogRichTextBlock()),
                    ("image", cms.blocks.BlogImageBlock()),
                ],
                null=True,
                use_json_field=True,
            ),
        ),
    ]
