# Generated by Django 4.1.1 on 2023-10-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cms", "0006_sitesettings_address_sitesettings_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="slug",
            field=models.CharField(
                choices=[("navbar", "Navbar"), ("footer", "Footer")],
                default="navbar",
                max_length=10,
                verbose_name="Slug",
            ),
        ),
    ]
