# Generated by Django 4.1.1 on 2023-10-05 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0042_remove_profile_activation_key_and_more"),
        ("accounts", "0015_alter_account_org"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="billing_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_billing_address",
                to="common.address",
            ),
        ),
        migrations.AddField(
            model_name="account",
            name="shipping_address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="account_shipping_address",
                to="common.address",
            ),
        ),
    ]
